apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"admissionregistration.k8s.io/v1","kind":"MutatingWebhookConfiguration","metadata":{"annotations":{},"name":"example-mutating-webhook"},"webhooks":[{"admissionReviewVersions":["v1beta1","v1"],"clientConfig":{"caBundle":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURpakNDQW5LZ0F3SUJBZ0lKQU9ZY0d0bWFkclQ0TUEwR0NTcUdTSWIzRFFFQkN3VUFNR2d4Q3pBSkJnTlYKQkFZVEFrTk9NUXN3Q1FZRFZRUUlEQUpIUkRFTE1Ba0dBMVVFQnd3Q1Uxb3hEREFLQmdOVkJBb01BM2g1YURFTApNQWtHQTFVRUN3d0NTVlF4SkRBaUJnTlZCQU1NRzNkbFltaHZiMnN0YzJWeWRtbGpaUzVrWldaaGRXeDBMbk4yCll6QWVGdzB5TXpBNE1EWXdNakkxTWpaYUZ3MHlNekE1TURVd01qSTFNalphTUdneEN6QUpCZ05WQkFZVEFrTk8KTVFzd0NRWURWUVFJREFKSFJERUxNQWtHQTFVRUJ3d0NVMW94RERBS0JnTlZCQW9NQTNoNWFERUxNQWtHQTFVRQpDd3dDU1ZReEpEQWlCZ05WQkFNTUczZGxZbWh2YjJzdGMyVnlkbWxqWlM1a1pXWmhkV3gwTG5OMll6Q0NBU0l3CkRRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFKaGJ0SHdlNTgxTGhDWmxNYmFiQWFHOVo5YkoKUXVVdHpDMGNUdzk0ek1uM1FTNWU2UEdyZVV4UTFIeXkrdlMvTzMzaUR6NzZDMkJVd2pCeHVTLzRWMVdVMVd6LwpUcmhPb05TYTE3QXFxSUlqT1A1bnh4T09nUDFjcVhnM0krR1ptM3RTNWNVVFRUejdOSnM1RUUrNjE0SmY1ek9sCjlLcG5NRmlDeE1UUllZeW1WQXlaQlI1d2kvVW5HQ2o3WVZQVFo4N2xFZ2dSMklGaURUaXJOVy94Wkx3WngycGsKREtkSWRYajdKRTVnb3d1OUZweW9rRnE2Z1V4N2JhNmJkZ3F2bXVrbGs1NHBPUUxYZysvSENGaUNjeUFDSVNNSgpxSHpuM3QyZXdGbGVVK1BrNTZVSlhJOXpxTmUxTTlicHkvSWRFZ0FjSnRDcllGUDZ5MEhBYUJtQWxzVUNBd0VBCkFhTTNNRFV3TXdZRFZSMFJCQ3d3S29JYmQyVmlhRzl2YXkxelpYSjJhV05sTG1SbFptRjFiSFF1YzNaamdndDMKZDNjdWVIbG9MbU52YlRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWg5ek9RUGlOZjNUVk5Qd1VOaDFhSDAvWApLdmdOYUF5bEQwMWhaL0I5ckw3SmVYOCt6ajZ5cVB3clc0QS9TVDdEQUtRK3d1bGtYTTk3SXlXZjBZd3ZvcTk4CjFyOXlDZmJlR1FCYk5QTkVhL0VtcHVPZkhuOGpBSmVhVjVnczZ4SjdmSlhEVzBYVHQzbk8rNEdnWWVzRDJid0QKTk5aRUZZODhuQmFwRERTMzkyVXhvUzZJRDdTT2J5eSs3OVdaWFRueXk2N0JBK1JnSVdzMURjeWhCaW1pQ29wOQozUFd2YStncDU1eTZWQjdpVzRReGRodDJieTNoRkFsUzU2TmNEUC9WdDFWVTJZM0R2cWZwZUdUcEFwbXFqU3ZnCjVmSjRYcHZHRHZwZ3VXR1JWcVFsNTB5ckN5d09LZ2VXUmxXaWcwL1JjRjF2UUFoekkvN05hT2paVFlMSUtRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=","service":{"name":"webhook-service","namespace":"default","path":"/mutate"}},"name":"webhook-service.default.svc","objectSelector":{"matchLabels":{"webhook-label":"special"}},"rules":[{"apiGroups":["*"],"apiVersions":["*"],"operations":["CREATE","UPDATE"],"resources":["pods"],"scope":"Namespaced"}],"sideEffects":"None"}]}
  creationTimestamp: "2023-08-06T01:53:50Z"
  generation: 2
  name: example-mutating-webhook
  resourceVersion: "13420"
  uid: 9aba86ec-360c-41b2-9d16-b5c4a4f5107e
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURpakNDQW5LZ0F3SUJBZ0lKQU9ZY0d0bWFkclQ0TUEwR0NTcUdTSWIzRFFFQkN3VUFNR2d4Q3pBSkJnTlYKQkFZVEFrTk9NUXN3Q1FZRFZRUUlEQUpIUkRFTE1Ba0dBMVVFQnd3Q1Uxb3hEREFLQmdOVkJBb01BM2g1YURFTApNQWtHQTFVRUN3d0NTVlF4SkRBaUJnTlZCQU1NRzNkbFltaHZiMnN0YzJWeWRtbGpaUzVrWldaaGRXeDBMbk4yCll6QWVGdzB5TXpBNE1EWXdNakkxTWpaYUZ3MHlNekE1TURVd01qSTFNalphTUdneEN6QUpCZ05WQkFZVEFrTk8KTVFzd0NRWURWUVFJREFKSFJERUxNQWtHQTFVRUJ3d0NVMW94RERBS0JnTlZCQW9NQTNoNWFERUxNQWtHQTFVRQpDd3dDU1ZReEpEQWlCZ05WQkFNTUczZGxZbWh2YjJzdGMyVnlkbWxqWlM1a1pXWmhkV3gwTG5OMll6Q0NBU0l3CkRRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFKaGJ0SHdlNTgxTGhDWmxNYmFiQWFHOVo5YkoKUXVVdHpDMGNUdzk0ek1uM1FTNWU2UEdyZVV4UTFIeXkrdlMvTzMzaUR6NzZDMkJVd2pCeHVTLzRWMVdVMVd6LwpUcmhPb05TYTE3QXFxSUlqT1A1bnh4T09nUDFjcVhnM0krR1ptM3RTNWNVVFRUejdOSnM1RUUrNjE0SmY1ek9sCjlLcG5NRmlDeE1UUllZeW1WQXlaQlI1d2kvVW5HQ2o3WVZQVFo4N2xFZ2dSMklGaURUaXJOVy94Wkx3WngycGsKREtkSWRYajdKRTVnb3d1OUZweW9rRnE2Z1V4N2JhNmJkZ3F2bXVrbGs1NHBPUUxYZysvSENGaUNjeUFDSVNNSgpxSHpuM3QyZXdGbGVVK1BrNTZVSlhJOXpxTmUxTTlicHkvSWRFZ0FjSnRDcllGUDZ5MEhBYUJtQWxzVUNBd0VBCkFhTTNNRFV3TXdZRFZSMFJCQ3d3S29JYmQyVmlhRzl2YXkxelpYSjJhV05sTG1SbFptRjFiSFF1YzNaamdndDMKZDNjdWVIbG9MbU52YlRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWg5ek9RUGlOZjNUVk5Qd1VOaDFhSDAvWApLdmdOYUF5bEQwMWhaL0I5ckw3SmVYOCt6ajZ5cVB3clc0QS9TVDdEQUtRK3d1bGtYTTk3SXlXZjBZd3ZvcTk4CjFyOXlDZmJlR1FCYk5QTkVhL0VtcHVPZkhuOGpBSmVhVjVnczZ4SjdmSlhEVzBYVHQzbk8rNEdnWWVzRDJid0QKTk5aRUZZODhuQmFwRERTMzkyVXhvUzZJRDdTT2J5eSs3OVdaWFRueXk2N0JBK1JnSVdzMURjeWhCaW1pQ29wOQozUFd2YStncDU1eTZWQjdpVzRReGRodDJieTNoRkFsUzU2TmNEUC9WdDFWVTJZM0R2cWZwZUdUcEFwbXFqU3ZnCjVmSjRYcHZHRHZwZ3VXR1JWcVFsNTB5ckN5d09LZ2VXUmxXaWcwL1JjRjF2UUFoekkvN05hT2paVFlMSUtRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: webhook-service
      namespace: default
      path: /mutate
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: webhook-service.default.svc
  namespaceSelector: {}
  objectSelector:
    matchLabels:
      webhook-label: special
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: Namespaced
  sideEffects: None
  timeoutSeconds: 10
