apiVersion: v1
kind: Service
metadata:
  name: webhook-service
spec:
  ports:
  - port: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: webhook-service
subsets:
  - addresses:
    - ip: 192.168.37.103
    ports:
    - port: 8080
